[general]
import = [
    #"~/.config/alacritty/themes/themes/catppuccin_frappe.toml"
    "~/.config/alacritty/themes/themes/tokyo_night.toml"
]

[terminal]
shell = { program = "/bin/zsh"}

[env]
TERM = "xterm-256color"

[font]
size = 7

[font.bold]
family = "SauceCodePro Nerd Font Mono"
style = "Bold"

[font.bold_italic]
family = "SauceCodePro Nerd Font Mono"
style = "Bold Italic"

[font.italic]
family = "SauceCodePro Nerd Font Mono"
style = "Italic"

[font.normal]
family = "SauceCodePro Nerd Font Mono"
style = "Regular"

[font.offset]
x = 0
y = 1

[window]
startup_mode = "Maximized"
